name: CI
on: [push]

env:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

jobs:
  build:
    runs-on: ubuntu-latest
    #services:
    #  docker:
    #    image: docker:dind
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest 
        
  #static_analysis:
  #lint_dockerfile:
    #stage: hadolint
    #image: hadolint/hadolint:latest-debian
    #before_script:
    #  - hadolint --version
    #script:
    #  - hadolint backend/Dockerfile
    #  - hadolint --ignore DL3007 mysql/Dockerfile
    #  - hadolint natl-frontend/Dockerfile
    #  - hadolint --ignore DL3013 tests/Dockerfile
  #unit_test:
  #integration_test:
  #deploy: